#!/usr/bin/env python3
"""Diff-aware coverage enforcement.

This helper reads the XML report generated by ``coverage.py`` (via pytest's
``--cov-report=xml`` flag) and ensures that any Python modules touched by the
current branch meet a minimum line coverage threshold.

Usage pattern::

    poetry run pytest --cov --cov-report=xml
    poetry run python scripts/ci/check_diff_coverage.py --base origin/main

When no ``--base`` is provided, the script falls back to ``$COVERAGE_BASE_REF``
(if set) and then tries to infer the upstream branch. Failures in git discovery
cause the check to become a no-op rather than breaking CI unexpectedly.
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Iterable

DEFAULT_THRESHOLD = 0.80


def _discover_repo_root() -> Path:
    """Locate the repository root by walking parent directories."""

    current = Path(__file__).resolve()
    for parent in current.parents:
        if (parent / ".git").exists():
            return parent
    # Fallback: assume script executed from repository root
    return Path.cwd()


def _normalise(path: str | os.PathLike[str], repo_root: Path) -> Path:
    candidate = Path(path)
    try:
        candidate = candidate.resolve()
        return candidate.relative_to(repo_root)
    except Exception:
        return candidate


def _resolve_base_ref(base_arg: str | None) -> str | None:
    if base_arg:
        return base_arg
    for env_var in ("COVERAGE_BASE_REF", "GITHUB_BASE_REF"):
        value = os.environ.get(env_var)
        if value:
            return value
    try:
        upstream = (
            subprocess.check_output(
                ["git", "rev-parse", "--abbrev-ref", "@{upstream}"],
                text=True,
                stderr=subprocess.DEVNULL,
            )
            .strip()
            .split("\n")[0]
        )
        return upstream or None
    except Exception:
        return None


def _changed_python_files(base_ref: str | None) -> list[Path]:
    if base_ref:
        diff_args = ["git", "diff", "--name-only", f"{base_ref}...HEAD"]
    else:
        diff_args = ["git", "diff", "--name-only", "HEAD"]
    try:
        output = subprocess.check_output(diff_args, text=True)
    except subprocess.CalledProcessError:
        return []
    paths = [Path(line.strip()) for line in output.splitlines() if line.strip()]
    return [p for p in paths if p.suffix == ".py"]


def _load_coverage(coverage_xml: Path, repo_root: Path) -> dict[Path, float]:
    if not coverage_xml.exists():
        raise FileNotFoundError(
            f"Coverage XML report not found at {coverage_xml!s}. Did you run pytest with --cov-report=xml?"
        )
    tree = ET.parse(coverage_xml)
    root = tree.getroot()
    coverage: dict[Path, float] = {}
    for class_node in root.findall(".//class"):
        filename = class_node.attrib.get("filename")
        if not filename:
            continue
        try:
            line_rate = float(class_node.attrib.get("line-rate", "0"))
        except ValueError:
            continue
        normalised = _normalise(filename, repo_root)
        coverage[normalised] = line_rate
    return coverage


def _filter_relevant(paths: Iterable[Path], repo_root: Path) -> list[tuple[Path, Path]]:
    """Return tuples of (display_path, coverage_key) for source files under alphaforge-brain/src."""

    relevant: list[tuple[Path, Path]] = []
    src_prefix = ("alphaforge-brain", "src")
    for original in paths:
        normalised = _normalise(original, repo_root)
        if len(normalised.parts) >= 3 and normalised.parts[:2] == src_prefix:
            coverage_key = Path(*normalised.parts[2:])
            relevant.append((normalised, coverage_key))
    return relevant


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--coverage-xml",
        type=Path,
        default=Path("coverage.xml"),
        help="Path to coverage.py XML report (default: coverage.xml)",
    )
    parser.add_argument(
        "--base",
        type=str,
        default=None,
        help="Git base ref to diff against (default: env/COVERAGE_BASE_REF or upstream)",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=DEFAULT_THRESHOLD,
        help="Per-file minimum coverage threshold (default: 0.80)",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print coverage for all touched files, not just failures",
    )
    args = parser.parse_args()

    repo_root = _discover_repo_root()
    coverage_map = _load_coverage(args.coverage_xml, repo_root)

    base_ref = _resolve_base_ref(args.base)
    changed_files = _changed_python_files(base_ref)
    relevant_files = _filter_relevant(changed_files, repo_root)

    if not relevant_files:
        print("[coverage] No relevant Python changes detected; skipping diff gate.")
        return 0

    failures: list[tuple[Path, float]] = []
    for display_path, coverage_key in relevant_files:
        rate = coverage_map.get(coverage_key)
        if rate is None:
            alt = Path("alphaforge-brain") / "src" / coverage_key
            rate = coverage_map.get(alt)
        if rate is None:
            failures.append((display_path, 0.0))
            continue
        if args.verbose:
            print(f"[coverage] {display_path}: {rate * 100:.1f}%")
        if rate + 1e-9 < args.threshold:
            failures.append((display_path, rate))

    if failures:
        print("[coverage] The following files are below the diff coverage threshold:")
        for path, rate in failures:
            print(
                f"  - {path}: {rate * 100:.1f}% (threshold {args.threshold * 100:.1f}%)"
            )
        print("[coverage] Run 'coverage xml' after pytest to regenerate the report.")
        return 1

    print(
        f"[coverage] All {len(relevant_files)} touched source files meet the {args.threshold * 100:.1f}% threshold."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
