"""Generate coverage policy artifact for governance dashboards.

Parses coverage XML generated by pytest-cov and writes
`zz_artifacts/coverage_policy.json` matching the CoverageThresholdPolicy schema.
"""

from __future__ import annotations

import argparse
import json
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_TARGET = 90
MODULE_TARGETS: dict[str, int] = {
    "services.equity": DEFAULT_TARGET,
    "services.execution": DEFAULT_TARGET,
    "services.metrics": DEFAULT_TARGET,
    "infra.cold_storage": DEFAULT_TARGET,
    "infra.time.timestamps": DEFAULT_TARGET,
    "infra.utils.hash": DEFAULT_TARGET,
}


@dataclass
class ModuleCoverage:
    line: float
    branch: float


def _parse_coverage(xml_path: Path) -> dict[str, ModuleCoverage]:
    try:
        tree = ET.parse(xml_path)
    except FileNotFoundError as exc:  # pragma: no cover - defensive
        raise SystemExit(f"coverage xml not found: {xml_path}") from exc
    except ET.ParseError as exc:  # pragma: no cover - defensive
        raise SystemExit(f"invalid coverage xml: {xml_path}") from exc

    modules: dict[str, ModuleCoverage] = {}
    root = tree.getroot()
    for cls in root.findall(".//class"):
        filename = cls.get("filename")
        if not filename:
            continue
        module = filename.replace("\\", ".").replace("/", ".")
        if module.endswith(".__init__"):
            module = module.rsplit(".", 1)[0]
        if module.endswith(".py"):
            module = module[:-3]
        if module.startswith(".."):  # pragma: no cover - unlikely relative path
            module = module[2:]
        for prefix in ("alphaforge-brain.src.", "src."):
            if module.startswith(prefix):
                module = module[len(prefix) :]
                break
        line_rate = float(cls.get("line-rate", "0")) * 100
        branch_rate = float(cls.get("branch-rate", "0")) * 100
        modules[module] = ModuleCoverage(line=line_rate, branch=branch_rate)
    return modules


def _build_policy(
    enforced_by: str, coverage: dict[str, ModuleCoverage]
) -> dict[str, object]:
    overrides: list[dict[str, int | str]] = []
    for module, target in MODULE_TARGETS.items():
        data = coverage.get(module)
        if data is None:
            raise SystemExit(f"coverage missing module '{module}'")
        if data.line < target:
            raise SystemExit(
                f"line coverage for {module} below target: {data.line:.2f}% < {target}%"
            )
        if data.branch < target:
            raise SystemExit(
                f"branch coverage for {module} below target: {data.branch:.2f}% < {target}%"
            )
        overrides.append({"module": module, "min_line": target, "min_branch": target})

    now = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    return {
        "target_line": DEFAULT_TARGET,
        "target_branch": DEFAULT_TARGET,
        "target_function": DEFAULT_TARGET,
        "target_integration": DEFAULT_TARGET,
        "module_overrides": overrides,
        "generated_at": now,
        "enforced_by": enforced_by,
    }


def write_policy(*, coverage_xml: Path, output: Path, enforced_by: str) -> None:
    coverage = _parse_coverage(coverage_xml)
    policy = _build_policy(enforced_by, coverage)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(policy, indent=2, sort_keys=True), encoding="utf-8")


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Write coverage policy artifact")
    parser.add_argument(
        "--coverage-xml",
        type=Path,
        default=Path("coverage.xml"),
        help="Path to coverage XML report",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("zz_artifacts/coverage_policy.json"),
        help="Destination for coverage policy JSON",
    )
    parser.add_argument(
        "--enforced-by",
        type=str,
        default="pytest",
        help="Identifier for the enforcing CI job",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv or sys.argv[1:])
    write_policy(
        coverage_xml=args.coverage_xml,
        output=args.output,
        enforced_by=args.enforced_by,
    )
    return 0


if __name__ == "__main__":  # pragma: no cover - manual execution
    raise SystemExit(main())
