name: Mind UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  a11y:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: alphaforge-mind
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: alphaforge-mind/package-lock.json
      - name: Install deps
        run: npm ci --no-audit --no-fund
      - name: Run accessibility tests (T092)
        run: npx vitest run tests/a11y

  perf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: alphaforge-mind
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: alphaforge-mind/package-lock.json
      - name: Install deps
        run: npm ci --no-audit --no-fund
      - name: Run performance tests (T090-T091)
        run: npx vitest run tests/perf

  # Aggregate status job (optional future): could depend on both and produce a badge artifact.
