name: OpenAPI Diff PR Comment

on:
  pull_request:
    paths:
      - 'specs/001-initial-dual-tier/contracts/openapi.yaml'

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install spec tooling
        run: npm ci --no-audit --no-fund

      - name: Run diff
        id: diff
        run: |
          node scripts/openapi/diff_report.js > diff_report.md || true
          echo "report<<EOF" >> $GITHUB_OUTPUT
          cat diff_report.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Add PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const report = process.env.REPORT || core.getInput('report');
            const fs = require('fs');
            const path = require('path');
            const body = fs.readFileSync('diff_report.md','utf-8');
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const marker = '<!-- openapi-diff-report -->';
            const existing = comments.find(c => c.body.includes(marker));
            const finalBody = `${marker}\n${body}`;
            if (existing) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existing.id,
                body: finalBody,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: finalBody,
              });
            }
